version: '3.5'

services:
  db:
    image: mysql:5.6
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: callcenter
      MYSQL_USER: callcenter
      MYSQL_PASSWORD: callcenter
    ports:
      - 3306:3306
