version: '3.5'

services:
  db:
    image: mysql:5.6
    network_mode: bridge
    environment:
      MYSQL_DATABASE: callcenter
      MYSQL_USER: callcenter
      MYSQL_PASSWORD: callcenter
      MYSQL_ROOT_PASSWORD: callcenter
    ports:
      - 3306:3306

  cache:
    image: redis:alpine
    network_mode: bridge
    ports:
      - 6379:6379
