import execute from '../lib/execute'
import defaultToZero from '../lib/defaultToZero'

const QUEUE_SUMMARY_UPDATE = `
  INSERT INTO queue_summary (
    queue_id,
    period,
    in_completed,
    in_transferred,
    in_abandoned,
    in_completed_sla,
    in_abandoned_sla,
    out_completed,
    out_transferred,
    out_discarded,
    auto_completed,
    auto_transferred,
    auto_discarded,
    auto_abandoned,
    in_call_secs,
    out_call_secs,
    auto_call_secs,
    in_hold_secs_completed,
    in_hold_secs_abandoned,
    out_try_secs_completed,
    out_try_secs_discarded,
    auto_hold_secs_completed,
    auto_hold_secs_abandoned,
    auto_try_secs_completed,
    auto_try_secs_discarded
  )
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  ON DUPLICATE KEY UPDATE
    in_completed = in_completed + VALUES(in_completed),
    in_transferred = in_transferred + VALUES(in_transferred),
    in_abandoned = in_abandoned + VALUES(in_abandoned),
    in_completed_sla = in_completed_sla + VALUES(in_completed_sla),
    in_abandoned_sla = in_abandoned_sla + VALUES(in_abandoned_sla),
    out_completed = out_completed + VALUES(out_completed),
    out_transferred = out_transferred + VALUES(out_transferred),
    out_discarded = out_discarded + VALUES(out_discarded),
    auto_completed = auto_completed + VALUES(auto_completed),
    auto_transferred = auto_transferred + VALUES(auto_transferred),
    auto_discarded = auto_discarded + VALUES(auto_discarded),
    auto_abandoned = auto_abandoned + VALUES(auto_abandoned),
    in_call_secs = in_call_secs + VALUES(in_call_secs),
    out_call_secs = out_call_secs + VALUES(out_call_secs),
    auto_call_secs = auto_call_secs + VALUES(auto_call_secs),
    in_hold_secs_completed = in_hold_secs_completed + VALUES(in_hold_secs_completed),
    in_hold_secs_abandoned = in_hold_secs_abandoned + VALUES(in_hold_secs_abandoned),
    out_try_secs_completed = out_try_secs_completed + VALUES(out_try_secs_completed),
    out_try_secs_discarded = out_try_secs_discarded + VALUES(out_try_secs_discarded),
    auto_hold_secs_completed = auto_hold_secs_completed + VALUES(auto_hold_secs_completed),
    auto_hold_secs_abandoned = auto_hold_secs_abandoned + VALUES(auto_hold_secs_abandoned),
    auto_try_secs_completed = auto_try_secs_completed + VALUES(auto_try_secs_completed),
    auto_try_secs_discarded = auto_try_secs_discarded + VALUES(auto_try_secs_discarded)
`

export default (mysql) => (summaryUpdate) => execute(mysql, QUEUE_SUMMARY_UPDATE, [
  summaryUpdate.queueId,
  summaryUpdate.period,
  summaryUpdate.inCompleted,
  summaryUpdate.inTransferred,
  summaryUpdate.inAbandoned,
  summaryUpdate.inCompletedSla,
  summaryUpdate.inAbandonedSla,
  summaryUpdate.outCompleted,
  summaryUpdate.outTransferred,
  summaryUpdate.outDiscarded,
  summaryUpdate.autoCompleted,
  summaryUpdate.autoTransferred,
  summaryUpdate.autoDiscarded,
  summaryUpdate.autoAbandoned,
  summaryUpdate.inCallSecs,
  summaryUpdate.outCallSecs,
  summaryUpdate.autoCallSecs,
  summaryUpdate.inHoldSecsCompleted,
  summaryUpdate.inHoldSecsAbandoned,
  summaryUpdate.outTrySecsCompleted,
  summaryUpdate.outTrySecsDiscarded,
  summaryUpdate.autoHoldSecsCompleted,
  summaryUpdate.autoHoldSecsAbandoned,
  summaryUpdate.autoTrySecsCompleted,
  summaryUpdate.autoTrySecsDiscarded
].map(defaultToZero))
